### ISSUE TITLE
CDATA breaks analysis 

### ISSUE THREAD

**Issue by gmella** [xqdoc/exist-xqdoc#14]
I succeeded to point an issue trying to use your great module on one of mine. 

One of it's function contains a CDATA inside an xml fragment of code. Next string seems to make the regenerate process fail:
`<![CDATA[ whatever ]]> `

Here is the error message I got:

`exerr:ERROR Error while parsing XML: The element type "xqdoc:body" must be terminated by the matching end-tag "</xqdoc:body>". [at line 63, column 48, source: /exist/etc/../data/expathrepo/xqdoc-0.5.5/content/xqdoc-module.xqm] In function: xqutil:generate-external-xqdoc(xs:anyURI) [59:12:/exist/etc/../data/expathrepo/xqdoc-0.5.5/content/xqdoc-module.xqm] xqutil:generate-external-xqdocs() [12:1:/exist/etc/../data/expathrepo/xqdoc-0.5.5/content/xqdoc-module.xqm]`

It would be nice if this could give location of code that breaks the process :)

Anyway, thaks a lot for this nice work!

Regards,

**Comment by lcahlander** [comment]
Please try version 0.5.7 in the repository.

https://github.com/xqdoc/exist-xqdoc/tree/main/releases <https://github.com/xqdoc/exist-xqdoc/tree/main/releases>

**Comment by gmella** [comment]
Thank you Loren for this new release that fixes this issue!
