### ISSUE TITLE
Incorrect version number in page header

### ISSUE THREAD

**Issue by joewiz** [xqdoc/exist-xqdoc#56]
I just installed v0.7.2. The page header shows "v0.6.3":

> <img width="484" alt="Screen Shot 2022-02-08 at 2 24 45 PM" src="https://user-images.githubusercontent.com/59118/153060663-8a0aaedf-b223-4a6c-8421-11eb69ff5ede.png">

**Comment by lcahlander** [comment]
Has bee fixed in version 0.7.3

**Comment by joewiz** [comment]
@lcahlander Thanks!
